# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

#: kitty has very powerful font management. You can configure
#: individual font faces and even specify special fonts for particular
#: characters.

font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

#: You can specify different fonts for the bold/italic/bold-italic
#: variants. The easiest way to select fonts is to run the `kitten
#: choose-fonts` command which will present a nice UI for you to
#: select the fonts you want with previews and support for selecting
#: variable fonts and font features. If you want to learn to select
#: fonts manually, read the font specification syntax
#: <https://sw.kovidgoyal.net/kitty/kittens/choose-fonts/#font-spec-
#: syntax>.

font_size 12.0

scrollback_lines 0
single_instance yes
disable_ligatures never
allow_remote_control no
dynamic_backgroung_opacity no
tab_powerline_style none
hide_window_decorations yes
window_margin_width 0
window_padding_width 0
repaint_delay 5
input_delay 1
sync_to_monitor no
scrollback_pager_history_size 1
screllback_fill_enlarged_window no
clipboard_control no
url_exclusion_rules none

# clear_all_shortcuts yes

#: remaining 240 colors as color16 to color255.

color0 #282828
color8 #928374

#: black

color1 #cc241d
color9 #fb4934

#: red

color2  #98971a
color10 #b8bb26

#: green

color3  #d79921
color11 #fabd2f

#: yellow

color4  #458588
color12 #83a598

#: blue

color5  #b16286
color13 #d3869b

#: magenta

color6  #689d6a
color14 #8ec07c

#: cyan

color7  #a89984
color15 #ebdbb2

#: white

# mark1_foreground black

#: Color for marks of type 1

# mark1_background #98d3cb
